algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var
i , soma : inteiro



inicio
soma := 0
para i de 1 ate 100 passo 2 faca
soma := soma + i 

fimpara
escreva(soma)


fimalgoritmo